blank_issues_enabled: false
contact_links:
  - name: Questions and Discussion
    url: https://github.com/iqbalmh18/brave-api/discussions
    about: Ask questions and discuss ideas in the GitHub Discussions forum.
